apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workspace1-myapp
  namespace: mogenius-argo-cd
  labels:
    managed-by: mogenius
    workspaceName: workspace1
spec:
  destination:
    name: in-cluster
    namespace: ns2
  syncPolicy:
    automated:
      prune: true
  project: mogenius
  source:
    repoURL: https://helm.mogenius.com/public
    targetRevision: 1.2.1
    chart: moac
    helm:
      releaseName: workspace1-myapp
      valuesObject:
        configmaps: []
        sealedSecrets: []
        controllers: []
        services: []
        ingresses:
          - ingress-my-container-image-ka59qa:
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
              labels:
                mo-app: my-container-image-ka59qa
              spec:
                ingressClassName: traefik
                rules:
                  - host: my-container-image-ka59qa-vmmcti.local.mogenius.io
                    http:
                      paths:
                        - backend:
                            service:
                              name: my-container-image-ka59qa
                              port:
                                number: 6379
                          path: /
                          pathType: Prefix
                tls:
                  - hosts:
                      - my-container-image-ka59qa-vmmcti.local.mogenius.io
                    secretName: my-container-image-ka59qa-tls
          - ingress-my-deployment2:
              labels:
                mo-app: my-deployment2
              spec:
                ingressClassName: traefik
                rules:
                  - host: my-deployment2-pnrnrv.local.mogenius.io
                    http:
                      paths:
                        - backend:
                            service:
                              name: my-deployment2
                              port:
                                number: 80
                          path: /
                          pathType: Prefix
        rawResources:
          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              annotations: {}
              name: my-container-image-o1xq6f
              namespace: ns2
            spec:
              progressDeadlineSeconds: 600
              replicas: 1
              revisionHistoryLimit: 10
              selector:
                matchLabels:
                  app: my-container-image-o1xq6f
              strategy:
                rollingUpdate:
                  maxSurge: 25%
                  maxUnavailable: 25%
                type: RollingUpdate
              template:
                metadata:
                  labels:
                    app: my-container-image-o1xq6f
                spec:
                  containers:
                    - image: nginx:latest
                      imagePullPolicy: Always
                      name: nginx
                      resources: {}
                      terminationMessagePath: /dev/termination-log
                      terminationMessagePolicy: File
                  dnsPolicy: ClusterFirst
                  imagePullSecrets:
                    - {}
                  restartPolicy: Always
                  schedulerName: default-scheduler
                  securityContext: {}
                  terminationGracePeriodSeconds: 30
