apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: behrang-test-app
  namespace: mogenius-argo-cd
  labels:
    managed-by: mogenius
spec:
  destination:
    name: in-cluster
    namespace: namespac1
  syncPolicy:
    automated:
      prune: true
  project: mogenius
  source:
    repoURL: https://helm.mogenius.com/public
    targetRevision: 1.2.1
    chart: moac
    helm:
      releaseName: behrang-test-app
      valuesObject:
        configmaps:
          - my-configmap:
              data:
                my-key: my-value
          - my-configmap3:
              data:
                my-key: my-value
                test: hallo
          - my-configmap2:
              data:
                my-key: my-value
                puja: test
        sealedSecrets: []
        controllers: []
        services: []
        ingresses: []
        rawResources:
          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              annotations:
                gitBranch: 33-hallo
                gitRepository: https://github.com/behrangalavi/nginx-repo.git
                gitWorkflow: mo-build-33-hallo.yaml
              labels:
                test: behargostest22
              name: test1
              namespace: namespac1
            spec:
              progressDeadlineSeconds: 600
              replicas: 1
              revisionHistoryLimit: 10
              selector:
                matchLabels:
                  app: test1
              strategy:
                rollingUpdate:
                  maxSurge: 25%
                  maxUnavailable: 25%
                type: RollingUpdate
              template:
                metadata:
                  labels:
                    app: test1
                spec:
                  containers:
                    - image: nginx:latest
                      imagePullPolicy: Always
                      name: test1
                      resources: {}
                      terminationMessagePath: /dev/termination-log
                      terminationMessagePolicy: File
                  dnsPolicy: ClusterFirst
                  restartPolicy: Always
                  schedulerName: default-scheduler
                  securityContext: {}
                  terminationGracePeriodSeconds: 30
