apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workspace-test
  namespace: mogenius-argo-cd
  labels:
    managed-by: mogenius
    workspaceName: workspace1
spec:
  destination:
    name: in-cluster
    namespace: namespac1
  syncPolicy:
    automated:
      prune: true
  project: mogenius
  source:
    repoURL: https://helm.mogenius.com/public
    targetRevision: 1.2.1
    chart: moac
    helm:
      releaseName: argo-workspace-test
      valuesObject:
        configmaps:
          - my-configmap:
              data:
                my-key: my-value2
          - my-configmap2:
              data:
                my-key: my-value
                puja: test
          - my-configmap3:
              data:
                my-key: my-value
                test: hallo
        sealedSecrets: []
        controllers: []
        services: []
        ingresses: []
        rawResources:
          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              annotations:
                gitBranch: 33-hallo
                gitRepository: https://github.com/behrangalavi/nginx-repo.git
                gitWorkflow: mo-build-33-hallo.yaml
              labels:
                test: behangargotest3333
              name: test1
              namespace: namespac1
            spec:
              progressDeadlineSeconds: 600
              replicas: 1
              revisionHistoryLimit: 10
              selector:
                matchLabels:
                  app: test1
              strategy:
                rollingUpdate:
                  maxSurge: 25%
                  maxUnavailable: 25%
                type: RollingUpdate
              template:
                metadata:
                  labels:
                    app: test1
                spec:
                  containers:
                    - env:
                        - name: test
                          value: hallo
                      image: nginx:latest
                      imagePullPolicy: Always
                      name: test1
                      resources:
                        limits:
                          cpu: 200m
                        requests:
                          cpu: 200m
                      terminationMessagePath: /dev/termination-log
                      terminationMessagePolicy: File
                  dnsPolicy: ClusterFirst
                  restartPolicy: Always
                  schedulerName: default-scheduler
                  securityContext: {}
                  terminationGracePeriodSeconds: 30
