apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: behrangtestpod
  namespace: mogenius-argo-cd
  labels:
    managed-by: mogenius
    mogenius-helm-repo-name: myrepo
spec:
  destination:
    name: in-cluster
    namespace: mcp-server
  syncPolicy:
    automated:
      prune: true
      enabled: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  project: mogenius
  source:
    repoURL: https://stefanprodan.github.io/podinfo
    targetRevision: 6.9.4
    chart: podinfo
    helm:
      releaseName: behrangtestpod
      valuesObject: null
